[package]
name = "csgo-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
source2-demo = { version = "^0.3.2", features = ["cs2"] }
memmap2 = "0.9.9"
clap = { version = "4.5.54", features = ["derive"] }
chrono = "0.4.43"